In [10]:
# Import libraries
import pandas as pd
import seaborn as sns

In [12]:
# Load dataset from seaborn
df = sns.load_dataset('titanic')

In [13]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [17]:
# save dataset in excel format
df.to_excel('titanic.xlsx', index= False)

In [ ]:
# 1- Filtering data
# Passenger whose age is greater then 30
df[df['age'] > 30]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
873,0,3,male,47.0,0,0,9.0000,S,Third,man,True,NaN,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [21]:
df[(df['age'] > 30) & (df['sex'] == 'male')]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
20,0,2,male,35.0,0,0,26.0000,S,Second,man,True,NaN,Southampton,no,True
21,1,2,male,34.0,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
867,0,1,male,31.0,0,0,50.4958,S,First,man,True,A,Southampton,no,True
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
873,0,3,male,47.0,0,0,9.0000,S,Third,man,True,NaN,Southampton,no,True
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [24]:
df[(df['age'] > 10) & (df['class'] == 'First')]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [ ]:
# Label-bassed-selection 
df.loc[df['fare'] > 100]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
27,0,1,male,19.00,3,2,263.0000,S,First,man,True,C,Southampton,no,False
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
88,1,1,female,23.00,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
118,0,1,male,24.00,0,1,247.5208,C,First,man,True,B,Cherbourg,no,False
195,1,1,female,58.00,0,0,146.5208,C,First,woman,False,B,Cherbourg,yes,True
215,1,1,female,31.00,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
258,1,1,female,35.00,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
268,1,1,female,58.00,0,1,153.4625,S,First,woman,False,C,Southampton,yes,False
269,1,1,female,35.00,0,0,135.6333,S,First,woman,False,C,Southampton,yes,True
297,0,1,female,2.00,1,2,151.5500,S,First,child,False,C,Southampton,no,False
299,1,1,female,50.00,0,1,247.5208,C,First,woman,False,B,Cherbourg,yes,False
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False
306,1,1,female,NaN,0,0,110.8833,C,First,woman,False,NaN,Cherbourg,yes,True
307,1,1,female,17.00,1,0,108.9000,C,First,woman,False,C,Cherbourg,yes,False
311,1,1,female,18.00,2,2,262.3750,C,First,woman,False,B,Cherbourg,yes,False
318,1,1,female,31.00,0,2,164.8667,S,First,woman,False,C,Southampton,yes,False
319,1,1,female,40.00,1,1,134.5000,C,First,woman,False,E,Cherbourg,yes,False
325,1,1,female,36.00,0,0,135.6333,C,First,woman,False,C,Cherbourg,yes,True
332,0,1,male,38.00,0,1,153.4625,S,First,man,True,C,Southampton,no,False
334,1,1,female,NaN,1,0,133.6500,S,First,woman,False,NaN,Southampton,yes,False
337,1,1,female,41.00,0,0,134.5000,C,First,woman,False,E,Cherbourg,yes,True
341,1,1,female,24.00,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
373,0,1,male,22.00,0,0,135.6333,C,First,man,True,NaN,Cherbourg,no,True
377,0,1,male,27.00,0,2,211.5000,C,First,man,True,C,Cherbourg,no,False
380,1,1,female,42.00,0,0,227.5250,C,First,woman,False,NaN,Cherbourg,yes,True
390,1,1,male,36.00,1,2,120.0000,S,First,man,True,B,Southampton,yes,False
393,1,1,female,23.00,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
435,1,1,female,14.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False
438,0,1,male,64.00,1,4,263.0000,S,First,man,True,C,Southampton,no,False
498,0,1,female,25.00,1,2,151.5500,S,First,woman,False,C,Southampton,no,False
505,0,1,male,18.00,1,0,108.9000,C,First,man,True,C,Cherbourg,no,False
527,0,1,male,NaN,0,0,221.7792,S,First,man,True,C,Southampton,no,True
537,1,1,female,30.00,0,0,106.4250,C,First,woman,False,NaN,Cherbourg,yes,True
544,0,1,male,50.00,1,0,106.4250,C,First,man,True,C,Cherbourg,no,False
550,1,1,male,17.00,0,2,110.8833,C,First,man,True,C,Cherbourg,yes,False
557,0,1,male,NaN,0,0,227.5250,C,First,man,True,NaN,Cherbourg,no,True
581,1,1,female,39.00,1,1,110.8833,C,First,woman,False,C,Cherbourg,yes,False
609,1,1,female,40.00,0,0,153.4625,S,First,woman,False,C,Southampton,yes,True
659,0,1,male,58.00,0,2,113.2750,C,First,man,True,D,Cherbourg,no,False
660,1,1,male,50.00,2,0,133.6500,S,First,man,True,NaN,Southampton,yes,False
679,1,1,male,36.00,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
689,1,1,female,15.00,0,1,211.3375,S,First,child,False,B,Southampton,yes,False
698,0,1,male,49.00,1,1,110.8833,C,First,man,True,C,Cherbourg,no,False
700,1,1,female,18.00,1,0,227.5250,C,First,woman,False,C,Cherbourg,yes,False
708,1,1,female,22.00,0,0,151.5500,S,First,woman,False,NaN,Southampton,yes,True
716,1,1,female,38.00,0,0,227.5250,C,First,woman,False,C,Cherbourg,yes,True
730,1,1,female,29.00,0,0,211.3375,S,First,woman,False,B,Southampton,yes,True
737,1,1,male,35.00,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
742,1,1,female,21.00,2,2,262.3750,C,First,woman,False,B,Cherbourg,yes,False
763,1,1,female,36.00,1,2,120.0000,S,First,woman,False,B,Southampton,yes,False
779,1,1,female,43.00,0,1,211.3375,S,First,woman,False,B,Southampton,yes,False
802,1,1,male,11.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False
856,1,1,female,45.00,1,1,164.8667,S,First,woman,False,NaN,Southampton,yes,False

In [35]:
# Filtering + selecting columns
df.loc[df['age']<30, ['age','fare','class']]

      age     fare   class
0    22.0   7.2500   Third
2    26.0   7.9250   Third
7     2.0  21.0750   Third
8    27.0  11.1333   Third
9    14.0  30.0708  Second
..    ...      ...     ...
883  28.0  10.5000  Second
884  25.0   7.0500   Third
886  27.0  13.0000  Second
887  19.0  30.0000   First
889  26.0  30.0000   First

[384 rows x 3 columns]

In [32]:
df.loc[10,'age']

np.float64(4.0)

In [42]:
# 3- .isin() (Membership check)
# specific rows + specific columns together
# Filtering multiple categories
df[df['class'].isin(['First','Second'])]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [44]:
# Range Filtering
df[df['age'].between(20, 40)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [49]:
# 5- Index-based selection
df.iloc[0:5, 1:5]

   pclass     sex   age  sibsp
0       3    male  22.0      1
1       1  female  38.0      1
2       3  female  26.0      0
3       1  female  35.0      1
4       3    male  35.0      0

In [ ]:
# 6- Selecting Columns
# single column -> series
df['age']
# multiple dataframe -> series
df[['age', 'fare']]

      age     fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [55]:
# Creating new column
df['age_double'] = df['age']*2
df['age_double']

0      44.0
1      76.0
2      52.0
3      70.0
4      70.0
       ...
886    54.0
887    38.0
888     NaN
889    52.0
890    64.0
Name: age_double, Length: 891, dtype: float64

In [56]:
# 8- Sorting data
df.sort_values(by='age')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_double
803,1,3,male,0.42,0,1,8.5167,C,Third,child,False,NaN,Cherbourg,yes,False,0.84
755,1,2,male,0.67,1,1,14.5000,S,Second,child,False,NaN,Southampton,yes,False,1.34
644,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False,1.50
469,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False,1.50
78,1,2,male,0.83,0,2,29.0000,S,Second,child,False,NaN,Southampton,yes,False,1.66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,0,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,no,True,NaN
863,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False,NaN
868,0,3,male,NaN,0,0,9.5000,S,Third,man,True,NaN,Southampton,no,True,NaN
878,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True,NaN
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,NaN

In [72]:
# Missing values
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
age_double     177
dtype: int64

In [ ]:
# Drop missing
# remove missing values
df.dropna()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_double
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,76.0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,70.0
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True,108.0
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False,8.0
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True,116.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False,94.0
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True,66.0
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False,112.0
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,38.0
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,52.0

In [68]:
# Fill missing
df['age'].fillna(df['age'].mean(), inplace=True)

C:\Users\danis\AppData\Local\Temp\ipykernel_6848\1055597372.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['age'].fillna(df['age'].mean(), inplace=True)

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: age, Length: 891, dtype: float64

In [76]:
print(df['age'].isnull().sum())
df.fillna({'age' : df['age'].mean()})

177

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_double
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,44.0
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,76.0
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,52.0
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,70.0
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,54.0
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,38.0
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,NaN
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,52.0
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,64.0

In [80]:
df['age'] = df['age'].fillna(df['age'].mean())
print(df['age'].isnull().sum())

0

In [81]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_double
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,44.0
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,76.0
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,52.0
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,70.0
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,54.0
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,38.0
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,NaN
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,52.0
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,64.0

In [82]:
print(df.isnull().sum())

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
age_double     177
dtype: int64

In [ ]:
# 10- Split data into groups 
df.groupby('sex')['survived'].mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [90]:
df_1 = df[['age', 'fare']]
df_2 = df[['embark_town']]

In [92]:
# 11- merging
df_3 = pd.merge(df_1, df_2, left_index=True, right_index= True)
df_3

           age     fare  embark_town
0    22.000000   7.2500  Southampton
1    38.000000  71.2833    Cherbourg
2    26.000000   7.9250  Southampton
3    35.000000  53.1000  Southampton
4    35.000000   8.0500  Southampton
..         ...      ...          ...
886  27.000000  13.0000  Southampton
887  19.000000  30.0000  Southampton
888  29.699118  23.4500  Southampton
889  26.000000  30.0000    Cherbourg
890  32.000000   7.7500   Queenstown

[891 rows x 3 columns]

In [ ]:
# ----- Apply ------
# It will takes each value in the age cloumn and adds 10 to it
df['age'].apply(lambda x: x + 10)

0      32.000000
1      48.000000
2      36.000000
3      45.000000
4      45.000000
         ...
886    37.000000
887    29.000000
888    39.699118
889    36.000000
890    42.000000
Name: age, Length: 891, dtype: float64

In [95]:
# value_count
df['age'].value_counts()

age
29.699118    177
24.000000     30
22.000000     27
18.000000     26
28.000000     25
            ...
24.500000      1
0.670000       1
0.420000       1
34.500000      1
74.000000      1
Name: count, Length: 89, dtype: int64

In [96]:
df.values

array([[0, 3, 'male', ..., 'no', False, 44.0],
       [1, 1, 'female', ..., 'yes', False, 76.0],
       [1, 3, 'female', ..., 'yes', True, 52.0],
       ...,
       [0, 3, 'female', ..., 'no', False, nan],
       [1, 1, 'male', ..., 'yes', True, 52.0],
       [0, 3, 'male', ..., 'no', True, 64.0]],
      shape=(891, 16), dtype=object)

In [ ]:
cols = df.columns.tolist()

['survived',
 'pclass',
 'sex',
 'age',
 'sibsp',
 'parch',
 'fare',
 'embarked',
 'class',
 'who',
 'adult_male',
 'deck',
 'embark_town',
 'alive',
 'alone',
 'age_double']

In [99]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [100]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
886     True
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [101]:
# get duplicate rows
df[df.duplicated()]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_double
47,1,3,female,29.699118,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True,NaN
76,0,3,male,29.699118,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True,NaN
77,0,3,male,29.699118,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,NaN
87,0,3,male,29.699118,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,NaN
95,0,3,male,29.699118,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
870,0,3,male,26.000000,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True,52.0
877,0,3,male,19.000000,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True,38.0
878,0,3,male,29.699118,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True,NaN
884,0,3,male,25.000000,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True,50.0
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,54.0

In [102]:
df.pivot_table(values='survived', index='sex')

        survived
sex
female  0.742038
male    0.188908

In [105]:
df.groupby('sex')['survived'].mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [106]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_double
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,44.0
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,76.0
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,52.0
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,70.0
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,54.0
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,38.0
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,NaN
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,52.0
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,64.0

In [108]:
# Find top 3 oldest passengers
df.nlargest(3, 'age')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_double
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True,160.0
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True,148.0
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True,142.0

In [113]:
# Count passengers per class
df['class'].value_counts()

class
Third     491
First     216
Second    184
Name: count, dtype: int64

In [114]:
# Find survival rate by gender & class
df.groupby('sex')['survived'].mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [116]:
# Remove duplicate rows (if any)
df = df.dropna()
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_double
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,76.0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,70.0
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True,108.0
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False,8.0
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True,116.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False,94.0
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True,66.0
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False,112.0
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,38.0
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,52.0